# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        default:
            toolbar: [ "bold", "italic", "link", "bulletedlist", "numberedlist", "image", "blockquote", "undo", "redo" ]
            uiColor: "#ffffff"
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
